### ISSUE TITLE
ocr-ncnn报错。。。

### ISSUE THREAD

**Issue by zlszhonglongshen** [cmdbug/YOLOv5_NCNN#14]
android_YOLOV5_NCNN/app/src/main/cpp/ocr/RRLib.cpp:223: error: undefined reference to 'cv::_InputArray::_InputArray(cv::MatExpr const&)'

大佬，玩你部署的ocr-lite的时候，报这个错。。帮忙看下

**Comment by WZTENG** [comment]
必现？Simple-Pose能运行？

**Comment by zlszhonglongshen** [comment]
> 必现？Simple-Pose能运行？
你之前没有添加ocr的时候，我这边运行没有问题的。

**Comment by WZTENG** [comment]
是点击ocr按钮错误还是全部都错。

**Comment by zlszhonglongshen** [comment]
> 是点击ocr按钮错误还是全部都错。

都起不来。
![image](https://user-images.githubusercontent.com/9023908/91376003-b0d40700-e84e-11ea-91c0-b94c57a3614a.png)

**Comment by WZTENG** [comment]
什么叫都起不来？？目标检测也不行？

**Comment by zlszhonglongshen** [comment]
> 什么叫都起不来？？目标检测也不行？

就是build 就报这个错了。

**Comment by zlszhonglongshen** [comment]
> > 什么叫都起不来？？目标检测也不行？
> 
> 就是build 就报这个错了。

这个应该是ocr单独的这个错了，之前没有ocr的时候  build没有问题的

**Comment by zlszhonglongshen** [comment]
> > > 什么叫都起不来？？目标检测也不行？
> > 
> > 
> > 就是build 就报这个错了。
> 
> 这个应该是ocr单独的这个错了，之前没有ocr的时候 build没有问题的

注释掉C:/Users/Administrator/Desktop/YOLOv5_NCNN-master/android_YOLOV5_NCNN/app/src/main/cpp/ocr/RRLib.cpp:223: error: undefined reference to 'cv::_InputArray::_InputArray(cv::MatExpr const&)'   这行代码就不报错了。。。

**Comment by zlszhonglongshen** [comment]
> > > > 什么叫都起不来？？目标检测也不行？
> > > 
> > > 
> > > 就是build 就报这个错了。
> > 
> > 
> > 这个应该是ocr单独的这个错了，之前没有ocr的时候 build没有问题的
> 
> 注释掉C:/Users/Administrator/Desktop/YOLOv5_NCNN-master/android_YOLOV5_NCNN/app/src/main/cpp/ocr/RRLib.cpp:223: error: undefined reference to 'cv::_InputArray::_InputArray(cv::MatExpr const&)' 这行代码就不报错了。。。

我看源码里面的代码也是这样子

**Comment by WZTENG** [comment]
代码有这句？我怎么没找到。。。

**Comment by WZTENG** [comment]
好像代码也没用，注释掉吧，，

**Comment by zlszhonglongshen** [comment]
> 代码有这句？我怎么没找到。。。

这句代码在RRLib.cpp里面。    现在编译出来以后，识别部分，没有结果
![image](https://user-images.githubusercontent.com/9023908/91509875-0b806800-e90e-11ea-8814-149d2014994a.png)

**Comment by WZTENG** [comment]
用的pc??

**Comment by zlszhonglongshen** [comment]
> 用的pc??

是的呀。

**Comment by WZTENG** [comment]
https://github.com/WZTENG/YOLOv5_NCNN/blob/8a815e8257fc3ee80336bcdf889670b8a5dc863d/android_YOLOV5_NCNN/app/src/main/cpp/ocr/ocr.cpp#L32-L46
取消这些注释，不使用后面的代码。后面是给安卓用的，安卓没有找到对应简洁的方法。

**Comment by zlszhonglongshen** [comment]
> https://github.com/WZTENG/YOLOv5_NCNN/blob/8a815e8257fc3ee80336bcdf889670b8a5dc863d/android_YOLOV5_NCNN/app/src/main/cpp/ocr/ocr.cpp#L32-L46
> 
> 
> 取消这些注释，不使用后面的代码。后面是给安卓用的，安卓没有找到对应简洁的方法。

已经调整了，调整以后，现在点击了detect以后，都是直接闪退。

**Comment by WZTENG** [comment]
？？？不是用的pc？？？

**Comment by zlszhonglongshen** [comment]
> ？？？不是用的pc？？？

大佬，我是刚开始搞这个。刚表达错误。是在pc上跑的Android studio 
![image](https://user-images.githubusercontent.com/9023908/91511218-cc541600-e911-11ea-96e5-7736b5a1302e.png)

也就是在这个上面，不知道为什么会识别不了文字

**Comment by WZTENG** [comment]
那你改回来吧，，用调试看下最后alphabetChinese的值是不是正常文字。

**Comment by zlszhonglongshen** [comment]
> 那你改回来吧，，用调试看下最后alphabetChinese的值是不是正常文字。

大佬。你的ndk以及SDK是什么版本的？  我在Ubuntu以及mac都总是提示找不到

![image](https://user-images.githubusercontent.com/9023908/91924895-76fb7880-ed06-11ea-96ff-29993f0e41b1.png)

**Comment by WZTENG** [comment]
你不是用pc正常的嘛？
local.properties里面的ndk这行直接删掉，然后在app中的build.gradle中指定ndk版本:ndkVersion '21.0.xxxxxxx'，再试一下
![image](https://user-images.githubusercontent.com/19603468/91925362-68619100-ed07-11ea-9dd2-ffe90c3115cb.png)
![image](https://user-images.githubusercontent.com/19603468/91925387-77e0da00-ed07-11ea-97be-3ece3e08f41d.png)

**Comment by zlszhonglongshen** [comment]
> 你不是用pc正常的嘛？
> local.properties里面的ndk这行直接删掉，然后在app中的build.gradle中指定ndk版本:ndkVersion '21.0.xxxxxxx'，再试一下
> ![image](https://user-images.githubusercontent.com/19603468/91925362-68619100-ed07-11ea-9dd2-ffe90c3115cb.png)
> ![image](https://user-images.githubusercontent.com/19603468/91925387-77e0da00-ed07-11ea-97be-3ece3e08f41d.png)

是呀，我在window下没有问题，因为中文乱码，我就换到了Ubuntu了，但是总是提示上面的报错，我这里都设置成你那样子了。但是还是提示找不到NDK

**Comment by zlszhonglongshen** [comment]
> > 你不是用pc正常的嘛？
> > local.properties里面的ndk这行直接删掉，然后在app中的build.gradle中指定ndk版本:ndkVersion '21.0.xxxxxxx'，再试一下
> > ![image](https://user-images.githubusercontent.com/19603468/91925362-68619100-ed07-11ea-9dd2-ffe90c3115cb.png)
> > ![image](https://user-images.githubusercontent.com/19603468/91925387-77e0da00-ed07-11ea-97be-3ece3e08f41d.png)
> 
> 是呀，我在window下没有问题，因为中文乱码，我就换到了Ubuntu了，但是总是提示上面的报错，我这里都设置成你那样子了。但是还是提示找不到NDK

在真机测试，ocr一直都是闪退。。上传照片以后就闪退了

**Comment by zlszhonglongshen** [comment]
> > > 你不是用pc正常的嘛？
> > > local.properties里面的ndk这行直接删掉，然后在app中的build.gradle中指定ndk版本:ndkVersion '21.0.xxxxxxx'，再试一下
> > > ![image](https://user-images.githubusercontent.com/19603468/91925362-68619100-ed07-11ea-9dd2-ffe90c3115cb.png)
> > > ![image](https://user-images.githubusercontent.com/19603468/91925387-77e0da00-ed07-11ea-97be-3ece3e08f41d.png)
> > 
> > 
> > 是呀，我在window下没有问题，因为中文乱码，我就换到了Ubuntu了，但是总是提示上面的报错，我这里都设置成你那样子了。但是还是提示找不到NDK
> 
> 在真机测试，ocr一直都是闪退。。上传照片以后就闪退了

其他的没有啥问题。

**Comment by WZTENG** [comment]
有没有错误信息

**Comment by zlszhonglongshen** [comment]
> 有没有错误信息

没有的。进入到ocr里面，上传图片几秒钟以后，就回到了原始界面了、

**Comment by WZTENG** [comment]
换张图片再试试，，我也碰过个别图片容易挂。

**Comment by roachsinai** [comment]
@cmdbug 我是生成的 apk 在安卓小米9上测试，点进 ocr beta 就闪退了，其他的都可以。
