### ISSUE TITLE
安装失败

### ISSUE THREAD

**Issue by qinweizhang-1** [cmdbug/YOLOv5_NCNN#17]
在android studio AVD模拟器上可以运行，但是在mumu模拟器和真机上安装失败，把sdk和ndk版本降低就一堆错，请问有啥解决路径吗

**Comment by WZTENG** [comment]
ncnn sdk最低24，但用了androidx部分特性要求26，所以sdk就26吧，ndk低点应该没事。建议用as4.0以上版本。

**Comment by qinweizhang-1** [comment]
现在配置是targetSdkVersion 29,  ndk19，minSdkVersion 24,as4.0.1，仍然是在avd上可以 ，但是真机上安装失败 ，

**Comment by qinweizhang-1** [comment]
> ncnn sdk最低24，但用了androidx部分特性要求26，所以sdk就26吧，ndk低点应该没事。建议用as4.0以上版本。

现在配置是targetSdkVersion 29, ndk19，minSdkVersion 24,as4.0.1，仍然是在avd上可以 ，但是真机上安装失败 ，

**Comment by qinweizhang-1** [comment]
> ncnn sdk最低24，但用了androidx部分特性要求26，所以sdk就26吧，ndk低点应该没事。建议用as4.0以上版本。

谢谢大佬 测试了一遍：minsdk 24, targetsdk和compilesdk 28,29都可以，ndk17,19,21都试了 avd上可以，真机仍然无法安装，但是minsdk最低24版本,  23就会报错

**Comment by qinweizhang-1** [comment]
> > ncnn sdk最低24，但用了androidx部分特性要求26，所以sdk就26吧，ndk低点应该没事。建议用as4.0以上版本。
> 
> 谢谢大佬 测试了一遍：minsdk 24, targetsdk和compilesdk 28,29都可以，ndk17,19,21都试了 avd上可以，真机仍然无法安装，但是minsdk最低24版本, 23就会报错

谢谢大佬 可以了 因为是android系统版本的原因，在android 9以上的可以，7就无法安装
