### ISSUE TITLE
yolov5的其他模型能直接替换yolov5s的模型运行么？

### ISSUE THREAD

**Issue by luqiang6q** [cmdbug/YOLOv5_NCNN#2]
@WZTENG 您好，请问用yolov5的其他模型转换成ncnn后能运行起来么

**Comment by WZTENG** [comment]
> @WZTENG 您好，请问用yolov5的其他模型转换成ncnn后能运行起来么

不能直接转换后替换，ncnn不支持切片，但模型代码中有切片操作，具体看原作的修改方法。
https://github.com/sunnyden/YOLOV5_NCNN_Android/issues/2

**Comment by panchengl** [comment]
您好，请问修改后必须要重训模型吗

**Comment by WZTENG** [comment]
> 您好，请问修改后必须要重训模型吗

应该是不需要的。我没有转换过只是测试了下NCNN框架。

**Comment by panchengl** [comment]
我直接修改后

> > 您好，请问修改后必须要重训模型吗
> 
> 应该是不需要的。我没有转换过只是测试了下NCNN框架。

我按照原文直接修改了common.py中的切片操作，然后再直接生成onnx，转换后放入apk中出现的框全部是错误的，我在想是不是一定得需要重训？

**Comment by WZTENG** [comment]
> 我直接修改后
> 
> > > 您好，请问修改后必须要重训模型吗
> > 
> > 
> > 应该是不需要的。我没有转换过只是测试了下NCNN框架。
> 
> 我按照原文直接修改了common.py中的切片操作，然后再直接生成onnx，转换后放入apk中出现的框全部是错误的，我在想是不是一定得需要重训？

查看这个
https://github.com/sunnyden/YOLOV5_NCNN_Android/issues/1

**Comment by panchengl** [comment]
> > 我直接修改后
> > > > 您好，请问修改后必须要重训模型吗
> > > 
> > > 
> > > 应该是不需要的。我没有转换过只是测试了下NCNN框架。
> > 
> > 
> > 我按照原文直接修改了common.py中的切片操作，然后再直接生成onnx，转换后放入apk中出现的框全部是错误的，我在想是不是一定得需要重训？
> 
> 查看这个
> [sunnyden/YOLOV5_NCNN_Android#1](https://github.com/sunnyden/YOLOV5_NCNN_Android/issues/1)

好的，非常谢谢，我再去试试

**Comment by Skr20200701** [comment]
你好，请问删除切片操作后，你在安卓中预测的框是不是都集中在左上角？我也遇到了同样的问题

**Comment by panchengl** [comment]
是的，预测都在左上角，并且预测出来的框都是错的，我暂时也没得到解决

**Comment by xinsuinizhuan** [comment]
你好，预测问题解决了吗？我调用，预测的结果为空，score都是很小的数？

**Comment by panchengl** [comment]
u can see this issues:
https://github.com/sunnyden/YOLOV5_NCNN_Android/issues/3

**Comment by hufangjian** [comment]
您好，我把slice修改成卷积了。转caffe都是没问题的。onnx转ncnn时
python -m onnxsim best_0810_3.onnx best_0810_3_sim.onnx 正常
onnx2ncnn报不支持：
<img width="609" alt="1" src="https://user-images.githubusercontent.com/30458099/91160405-f2a06880-e6fb-11ea-9ea5-54386ca0bed7.png">

**Comment by reachzxsframe** [comment]
Unsupported slice axes !
Expand not supported yet!
ScatterND not supported yet!
Unsupported slice axes !
Expand not supported yet!
ScatterND not supported yet!
Unsupported slice axes !
Expand not supported yet!
ScatterND not supported yet!
Unsupported slice axes !
Expand not supported yet!
ScatterND not supported yet!
Unsupported slice axes !
Expand not supported yet!
ScatterND not supported yet!
Unsupported slice axes !
Expand not supported yet!
ScatterND not supported yet!

我也碰到这问题了，有哪位大佬知道这是什么原因？

**Comment by WZTENG** [comment]
https://blog.csdn.net/qq_33160678/article/details/108848264
