### ISSUE TITLE
yolov5s的onnx转ncnn模型的问题

### ISSUE THREAD

**Issue by zxy464430447** [cmdbug/YOLOv5_NCNN#24]
大佬好，目前yolov5基于Release v3版本的模型文件从onnx转ncnn的时候文件只有17M，模型被截断了，ncnn加载模型文件的时候会失败（返回-1），请问这可能是什么原因呀？

**Comment by WZTENG** [comment]
先用v1版本的先学下流程，v2、v3的没有试过。。
