### ISSUE TITLE
yolov5s和yolov4-tiny的速度为什么差的很多？

### ISSUE THREAD

**Issue by yao-zheng-yi** [cmdbug/YOLOv5_NCNN#25]
你好，这几天我尝试着跑了一下你的项目，发现yolov5s的fps只有5左右，而yolov4-tiny的fps有二十几，请问为什么会差这么多？
有什么方法可以提高yolov5s的fps吗

**Comment by cmdbug** [comment]
v4导出模型包含后处理，v5导出模型没有包含后处理。

**Comment by yao-zheng-yi** [comment]
> v4导出模型包含后处理，v5导出模型没有包含后处理。

感谢回复，请问v5后处理部分的代码有办法优化吗，感觉decode_infer函数里的4个for循环占用了大量时间，但是现在找不到方法去掉几个for加快推理速度。

**Comment by yao-zheng-yi** [comment]
> v4导出模型包含后处理，v5导出模型没有包含后处理。

万分感谢你的回复。
请问可以把yolov5得到的.pt文件通过u版yolov3的model.py转成.weights文件，然后再通过ncnn的darknet2ncnn转化吗？
但是如果这样可行的话，存在一个问题，model.py转化需要cfg文件，但是yolov5用的是yaml文件，请问该如何解决？

**Comment by cmdbug** [comment]
把yaml看懂转写成cfg，其它的暂时也想不到解决方法。直接魔改v5的工程不包含切片也够呛。
