### ISSUE TITLE
你好，请问那个yolov4-tiny版本是跑darknet转的吗

### ISSUE THREAD

**Issue by Chinajuedui** [cmdbug/YOLOv5_NCNN#3]

**Comment by WZTENG** [comment]
yolov4鹅厂官方ncnn模型下载地址
darknet2ncnn:https://drive.google.com/drive/folders/1YzILvh0SKQPS_lrb33dmGNq7aVTKPWS0
从ncnn官方说明是用darknet2ncnn转换来的。

original pretrained model from https://github.com/AlexeyAB/darknet
the ncnn model https://drive.google.com/drive/folders/1YzILvh0SKQPS_lrb33dmGNq7aVTKPWS0?usp=sharing
the ncnn model https://github.com/nihui/ncnn-assets/tree/master/models
