### ISSUE TITLE
怎么样去掉OPENCV啊？

### ISSUE THREAD

**Issue by 9175554** [cmdbug/YOLOv5_NCNN#30]
按您的例子直接打开这个YOLOV5的自定义层的例子，一进去就闪退，看YoloV5CustomLayer.h 里面写了：
ncnn 与 opencv 库冲突，需要重新编译 ncnn 或去掉 opencv 。（该项目保留 opencv ，如果需要两者都支持请看下面说明）
请问怎么样去掉OPENCV啊？

**Comment by cmdbug** [comment]
安卓的话，建议重新编译ncnn来的方便。cmake xxxxxxxxxxx
 -DNCNN_DISABLE_RTTI=OFF -DNCNN_DISABLE_EXCEPTION=OFF ..
iOS直接在设置里面配置，看iOS文件的说明，iOS暂时不需要重新编译。

**Comment by cmdbug** [comment]
安卓：如果没有opencv的话，直接CMakeLists.txt加上这个就不需要重新编译ncnn
# disable rtti and exceptions
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fno-rtti -fno-exceptions")
