### ISSUE TITLE
How to use a different model file (.pt)

### ISSUE THREAD

**Issue by alex-imperfect** [cmdbug/YOLOv5_NCNN#35]
We're trying to use Yolov4 and yolov5 but with a different model file. We have a .pt file.

Is it possible for us to replace the model file to test it with this project?

**Comment by cmdbug** [comment]
.pt -> .onnx -> ncnn

**Comment by cmdbug** [comment]
https://zhuanlan.zhihu.com/p/275989233?utm_source=qq
