### ISSUE TITLE
我训练了yolov5自己的模型，类别是1，在转成ncnn替换了YOLOv5_NCNN-master\iOS_YOLOv5NCNN\YOLOv5NCNN\res\

### ISSUE THREAD

**Issue by Nabyssache** [cmdbug/YOLOv5_NCNN#37]
我训练了yolov5自己的模型，类别是1，在转成ncnn替换了YOLOv5_NCNN-master\iOS_YOLOv5NCNN\YOLOv5NCNN\res\yolov5.bin 和yolov5.param之后执行demo报错
2021-01-18 11:00:43.932899+0800 NCNN Demo[9473:20535076] new YoloV5
layer Shape_246 not exists or registered
我用的是最新版本的yolov5，version3训练的，我想知道作者yolov5demo用的是那个版本的？还有一个就是我修改了训练类别，这个直接替换文件还需要做什么操作吗？

**Comment by cmdbug** [comment]
推荐使用 yolov5_custom_op 精度会高点
https://zhuanlan.zhihu.com/p/275989233
v3版本可以，v4没弄过。
注意修改 h 文件里面对应的输出blob

yolov5s这个可以根据这个改，但不推荐。
https://blog.csdn.net/qq_33160678/article/details/108848264?utm_medium=distribute.pc_relevant.none-task-blog-BlogCommendFromMachineLearnPai2-11.control&depth_1-utm_source=distribute.pc_relevant.none-task-blog-BlogCommendFromMachineLearnPai2-11.control
同样注意 h 文件对应blob值的修改

类别也是修改 h 文件对应的值。

**Comment by cmdbug** [comment]
如果有用opencv暂时使用的是2.4.13版本，或者尝试下大佬的版本
https://github.com/nihui/opencv-mobile

**Comment by Nabyssache** [comment]
yolov5的版本号有点多，这个CSDN的教程是version2的版本的；我只想跑通自己的demo，https://github.com/dog-qiuqiu/MobileNet-Yolo 请问yolov3用的是这个项目里的哪个模型呢

**Comment by cmdbug** [comment]
yolov3-nano版，直接darknet2ncnn转换

**Comment by Nabyssache** [comment]
模型转换好了直接替换就可以了是吗？需不需要修改某些配置？

**Comment by cmdbug** [comment]
大部分改 h文件就行了，类别数，尺寸，输出blob，其它应该不用。动手试下就知道了。

**Comment by Nabyssache** [comment]
作者你好，我照着csdn说的重新转换的NCNN，修改了YOLOV5.h文件里的classes 和 labels，但是blob是什么我不知道，所以没修改，现在报错了：
···
new YoloV5
net load param and model success!find_blob_index_by_name 394 failed
find_blob_index_by_name 375 failed
···

请问这个是什么原因，我现在的yolov5.h文件是这样子的：
···
//
//  YoloV5.hpp
//  YOLOv5NCNN
//
//  Created by WZTENG on 2020/7/6.
//  Copyright © 2020 TENG. All rights reserved.
//

#ifndef YoloV5_hpp
#define YoloV5_hpp

#include <stdio.h>
#include "ncnn/ncnn/net.h"
#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>
#import <UIKit/UIImage.h>
#import <functional>

namespace yolocv {
    typedef struct {
        int width;
        int height;
    }YoloSize;
}

typedef struct {
    std::string name;
    int stride;
    std::vector<yolocv::YoloSize> anchors;
}YoloLayerData;

typedef struct BoxInfo {
    float x1;
    float y1;
    float x2;
    float y2;
    float score;
    int label;
}BoxInfo;

class YoloV5 {
public:
    YoloV5(bool useGPU);
    ~YoloV5();
    std::vector<BoxInfo> dectect(UIImage *image, float threshold, float nms_threshold);
    std::vector<std::string> labels{"fish"};

private:
    static std::vector<BoxInfo> decode_infer(ncnn::Mat &data, int stride, const yolocv::YoloSize& frame_size, int net_size, int num_classes, const std::vector<yolocv::YoloSize>& anchors, float threshold);
    static void nms(std::vector<BoxInfo>& result, float nms_threshold);
    
    ncnn::Net* Net;
    int input_size = 640;
    int num_class = 1;
    std::vector<YoloLayerData> layers{
        {"394", 32, {{116, 90}, {156, 198}, {373, 326}}},
        {"375", 16, {{30, 61}, {62, 45}, {59, 119}}},
        {"output", 8, {{10, 13}, {16, 30}, {33, 23}}},
    };
    
public:
    static YoloV5 *detector;
    static bool hasGPU;
    static bool toUseGPU;
    
};


#endif /* YoloV5_hpp */

···

需要修改的地方是哪个呢？谢谢！

**Comment by cmdbug** [comment]
```c++
std::vector<YoloLayerData> layers{
    {"394", 32, {{116, 90}, {156, 198}, {373, 326}}},
    {"375", 16, {{30, 61}, {62, 45}, {59, 119}}},
    {"output", 8, {{10, 13}, {16, 30}, {33, 23}}},
};
```
用netron打开 param 查看对应的输出名称。注意对应的数字相应的输出。

**Comment by cmdbug** [comment]
https://github.com/cmdbug/TNN_Demo/issues/1
修改blob过程看后面几步的图示，大概意思是一样的。就是用netron打开看输出名称，然后修改h文件layers里面对应的位置。

**Comment by Nabyssache** [comment]
可能是内网的原因，这个网页的图片我无法查看。我用netron打开这个项目里的yolov5.param, 并没有看到394，375这几个name的层，后面的数字表示什么意思？不知道从哪里开始修改，可不可以把图片发到我的邮箱 1800211003@email.szu.edu.cn。或者我把我的param文件发送给你，你指导一下我可以吗？

**Comment by Nabyssache** [comment]
我现在已经修改好了这三个输出层，但是后面又有了新的错误：

ex.extract(layer.name.c_str(), blob);
----
std::vector<BoxInfo> YoloV5::dectect(UIImage *image, float threshold, float nms_threshold)
这个方法里面

好像又回到blob了

**Comment by cmdbug** [comment]
太抽象

**Comment by Nabyssache** [comment]
在extract方法中出的错，由于封装起来了，所以看不到具体错误在哪里。。
ex对象和layer对象都不为空，是正常的。

--------
Printing description of ex:
(ncnn::Extractor) ex = {
  net = 0x0000000281064100
  blob_mats = size=204 {
    std::__1::__vector_base<ncnn::Mat, std::__1::allocator<ncnn::Mat> > = {
      __begin_ = 0x00000001060cc200
      __end_ = 0x00000001060cf500
      __end_cap_ = {
        std::__1::__compressed_pair_elem<ncnn::Mat *, 0, false> = {
          __value_ = 0x00000001060cf500
        }
      }
    }
  }
  opt = {
    lightmode = true
    num_threads = 4
    blob_allocator = 0x0000000000000000
    workspace_allocator = 0x0000000000000000
    openmp_blocktime = 20
    use_winograd_convolution = true
    use_sgemm_convolution = true
    use_int8_inference = true
    use_vulkan_compute = false
    use_fp16_packed = true
    use_fp16_storage = true
    use_fp16_arithmetic = true
    use_int8_storage = true
    use_int8_arithmetic = false
    use_packing_layout = true
    use_shader_pack8 = false
    use_subgroup_basic = false
    use_subgroup_vote = false
    use_subgroup_ballot = false
    use_subgroup_shuffle = false
    use_image_storage = false
    use_bf16_storage = false
    use_weight_fp16_storage = false
  }
}
--------
Printing description of layer:
(const value_type &) layer = 0x0000000280954d48: {
  name = "377"
  stride = 16
  anchors = size=3 {
    std::__1::__vector_base<yolocv::YoloSize, std::__1::allocator<yolocv::YoloSize> > = {
      __begin_ = 0x0000000283e170e0
      __end_ = 0x0000000283e170f8
      __end_cap_ = {
        std::__1::__compressed_pair_elem<yolocv::YoloSize *, 0, false> = {
          __value_ = 0x0000000283e170f8
        }
      }
    }
  }
}

-------
这个方法应该是从layer中获取对象到blob，这个过程中出错了。

**Comment by cmdbug** [comment]
没改模型或其它模型正常？

**Comment by Nabyssache** [comment]
我跑的通这个项目下的IOS所有模型demo，我用yolov5s训练的模型，我把我的bin 和param把 iOS_YOLOv5NCNN\YOLOv5NCNN\res里的yolov5.bin yolov5.param 覆盖掉直接使用的。

**Comment by cmdbug** [comment]
按教程重新检查转换步骤。。。其它暂时也不清楚了QAQ

**Comment by Nabyssache** [comment]
好吧，谢谢你这么耐心。我去试试yolo-nano把

**Comment by cmdbug** [comment]
我是怕你哪里转换有错，，，代码应该是没问题的。。除了修改部分 h文件内容。。或者不要用你自己训练的，，直接用官方的模型权重转换一下，看下是不是转换过程是对的。

**Comment by Nabyssache** [comment]
我现在用以前训练的yolov4-tiny模型，直接用darknet2ncnn转成功了，用了./ncnnoptimize yolov4-tiny.param yolov4-tiny.bin yolov4-tiny-opt.param yolov4-tiny-opt.bin 0优化
请问我要改yolov4.h文件吗，我看只有输入size和classes能改，我用netron打开param发现输出只有一层，但是我cfg里面的yolo head有两个。

-----------
我用yolov5自带的export.py 生成了onnx， 然后照着这里blog.csdn.net/qq_33160678/article/details/108848264?utm_medium=distribute.pc_relevant.none-task-blog-BlogCommendFromMachineLearnPai2-11.control&depth_1-utm_source=distribute.pc_relevant.none-task-blog-BlogCommendFromMachineLearnPai2-11.control
修改common.py切片操作， 在转成NCNN的过程中也没有任何报错和告警

-------------

**Comment by cmdbug** [comment]
yolov4-tiny这个后处理ncnn内部集成了。
yolov5s这个要自己放到工程里面试才知道，根据步骤修改相关参数。

**Comment by Nabyssache** [comment]
yolov4-tiny跑通了，谢谢！！

**Comment by cmdbug** [comment]
有空可以试试 TNN 版本yolov5
https://github.com/cmdbug/TNN_Demo/
转换教程
https://github.com/cmdbug/TNN_Demo/issues/1
