### ISSUE TITLE
请问一下这个问题，是需要在cmake里指定吗，我改成了ncnn或者ncnnvulkan都不行

### ISSUE THREAD

**Issue by 1372072273** [cmdbug/YOLOv5_NCNN#39]
C/C++ debug|armeabi-v7a : CMake Error at app\src\main\cpp\CMakeLists.txt:103 (target_link_libraries):
  Cannot specify link libraries for target "yolov5" which is not built by
  this project.

**Comment by cmdbug** [comment]
没编译成功？清清缓存试试

**Comment by cmdbug** [comment]
试试在CMakeLists.txt打个空格什么的，让CMakeLists重新编译一下，，

**Comment by 1372072273** [comment]
我把cmkae里
add_library( # Sets the name of the library.
        yolov5

        # Sets the library as a shared library.
        SHARED

        # Provides a relative path to your source file(s).
        jni_interface.cpp
        YoloV5.cpp
        YoloV4.cpp
        SimplePose.cpp
        Yolact.cpp
        ocr/clipper.cpp
        ocr/NCNNDBNet.cpp
        ocr/ocr.cpp
        ocr/RRLib.cpp
        ocr/ZUtil.cpp
        ENet.cpp
        FaceLandmark.cpp
        DBFace.cpp
        MbnFCN.cpp
        MobileNetV3Seg.cpp
        YoloV5CustomLayer.cpp
        NanoDet.cpp
        )
注释的这一段给放了出来，编译就可以了

**Comment by cmdbug** [comment]
改之前
aux_source_directory(. SRC_LIST)
改之后
aux_source_directory(./ SRC_LIST)
其实就是让重新编译一下，我就是这么搞的，如果有新的 c 文件再把 / 删掉，不断反复就行了。每个 c 文件都加一个麻烦。

**Comment by 1372072273** [comment]
嗯嗯 ，谢谢博主回答！
