### ISSUE TITLE
Merge our project? YOLOV4 tiny + lane detection on Android with 8 FPS!

### ISSUE THREAD

**Issue by youkpan** [cmdbug/YOLOv5_NCNN#40]
YOLOV4 tiny + lane detection on Android with 8 FPS!

Tested with HONOR 20PRO
Test video :

https://www.bilibili.com/video/BV1xv411e7zJ/

https://www.bilibili.com/video/BV18K4y1n7Ht/

<img width="100%" src="https://github.com/youkpan/Hayoou_safe_driving_android/blob/master/screenshot.jpg"/>

Published at :
http://hayoou.com/adas

APP download ：https://pan.baidu.com/s/1Q-huWTcHGWfyD8AXxVoyow 
code：adas 

open souce :

[https://github.com/youkpan/hayoou_safe_driving_android](https://github.com/youkpan/hayoou_safe_driving_android)

**Comment by cmdbug** [comment]
有空看看。

**Comment by cmdbug** [comment]
实测效果不是很好，对位置角度什么的要求比较高，QAQ
