### ISSUE TITLE
关于yolov4-tiny

### ISSUE THREAD

**Issue by Wangbenzhi** [cmdbug/YOLOv5_NCNN#43]
作者您好！我注意到您的代码中yolov4-tiny包含后处理过程，我现在想重新训练yolov4-tiny的权重，所以想请教一下您是选用的是哪个版本的yolov4-tiny（看您首页给的链接是u版的yolov3？）

**Comment by cmdbug** [comment]
darknet版的权重就行，转换用的是darknet2ncnn直接转换，u版跟AB版应该都可以用。

**Comment by cmdbug** [comment]
.cfg 跟 .weight 文件转换

**Comment by Wangbenzhi** [comment]
抱歉还是有些疑惑，您yolov4-tiny用的是yolov3的权重吗？

**Comment by cmdbug** [comment]
AB版的就可以，U版的cfg里面也有v4-tiny的cfg文件啊。只要工程支持 .cfg 与 .weight 权重这行，保存成 .weight 后用 darknet2ncnn 直接转成 ncnn。.pt文件没试过。

**Comment by Wangbenzhi** [comment]
感谢感谢！ 找到了，u版的cfg文件在archive分支中
