### ISSUE TITLE
Why need convert from RGB to BGR

### ISSUE THREAD

**Issue by wwdok** [cmdbug/YOLOv5_NCNN#48]
Hello, i noticed that preprocess() in NanoDet.cpp, there is a line of code : 
`in = ncnn::Mat::from_android_bitmap_resize(env, image, ncnn::Mat::PIXEL_RGBA2BGR, input_size, input_size);`
I want to know why we need to convert RGB to BGR,  ncnn's default channel order is BGR ? Thanks in advance !

**Comment by cmdbug** [comment]
The input of nanodet is BGR

**Comment by wwdok** [comment]
Got it, thank you !

**Comment by ruiming46zrm** [comment]
why did I use your nanodet ouput wrong boxes but it is correct when i use nanodet offical ncnn demo
