### ISSUE TITLE
关于部署ios的一个问题

### ISSUE THREAD

**Issue by wangxinzhe0617** [cmdbug/YOLOv5_NCNN#56]
您好！我想请教一下您 我ios版本使用的模拟器 build succes之后 ![image](https://user-images.githubusercontent.com/38687226/119631236-46361300-be42-11eb-8793-631c9a064026.png)出现这个提示 不知道该怎么解决希望得到您的帮助 非常感谢！

**Comment by cmdbug** [comment]
没试过模拟器

**Comment by wangxinzhe0617** [comment]
> 没试过模拟器

您好！感谢回复，好像是ncnn不支持模拟器。
