### ISSUE TITLE
下载的模型放在什么位置？

### ISSUE THREAD

**Issue by Zengyf-CVer** [cmdbug/YOLOv5_NCNN#57]
@cmdbug 
#### 从git clone下来的项目之后，将下载的模型放在项目中的什么具体位置，才能让程序运行起来？

**Comment by cmdbug** [comment]
Android? iOS ? 安卓的模型已经在工程里面了，iOS的从安卓对应目录复制过去。

**Comment by Zengyf-CVer** [comment]
> Android? iOS ? 安卓的模型已经在工程里面了，iOS的从安卓对应目录复制过去。
