### ISSUE TITLE
FPS 感觉有点低啊，请问这是正常的吗

### ISSUE THREAD

**Issue by wh0x** [cmdbug/YOLOv5_NCNN#6]
老哥，我看你截图里的FPS，感觉有点低，请问这是正常的吗，对这方面不是很了解。。。。

**Comment by WZTENG** [comment]
yolov5s在手机端进行后处理有几层for进行nms所以会感觉慢，但yolov4-tiny的直接显示结果，大约会快5倍左右。

**Comment by WZTENG** [comment]
如果模型导出处理好的话，在性能高的手机可以大于20帧

**Comment by wh0x** [comment]
for 循环nms那个有比较好的处理方法吗？参考了鹅厂的demo，发现它们nms似乎直接放进模型中去了，没有这种显示的nms，可能是darknet直接转的原因？感觉要这样的话，pytorch得到的模型感觉很难较好地部署Android端啊，这FPS实在接受不了，找了一些demo，感觉都是像鹅厂demo那样直接输出结果，没有显示的调用nms。

**Comment by WZTENG** [comment]
> for 循环nms那个有比较好的处理方法吗？参考了鹅厂的demo，发现它们nms似乎直接放进模型中去了，没有这种显示的nms，可能是darknet直接转的原因？感觉要这样的话，pytorch得到的模型感觉很难较好地部署Android端啊，这FPS实在接受不了，找了一些demo，感觉都是像鹅厂demo那样直接输出结果，没有显示的调用nms。

这个是模型导出时有没有把后处理一起集成到模型的问题，建议先用u版的yolov3去学习下怎么导出。可以在导出模型时把后处理部分的代码也一起集成到模型中就行了。
会yolov3导出后应该就知道怎么导v5了，但由于yolov5有一个地方用了切片需要改一个地方。yolov5详细导出可以查看这个：
https://github.com/sunnyden/YOLOV5_NCNN_Android/issues/3

**Comment by WZTENG** [comment]
最新的代码有yolov4-tiny跟mobilenetv2_yolov3_nano的示例。

**Comment by wh0x** [comment]
u版yolov3里似乎也没有集成。。。https://github.com/ultralytics/yolov3/issues/288#issuecomment-493664054，不知v4 tiny他们咋转的

**Comment by WZTENG** [comment]
> u版yolov3里似乎也没有集成。。。[https://github.com/ultralytics/yolov3/issues/288#issuecomment-493664054，不知v4](https://github.com/ultralytics/yolov3/issues/288#issuecomment-493664054%EF%BC%8C%E4%B8%8D%E7%9F%A5v4) tiny他们咋转的

训练后会保存 .pt 文件，使用model.py的转换方法转成 .weights 文件，再使用 ncnn 的 darknet2ncnn.cpp 生成就行了。
