### ISSUE TITLE
有关int8推理的一些问题

### ISSUE THREAD

**Issue by Zr2223** [cmdbug/YOLOv5_NCNN#64]
您好，请问如果我想进行int8推理的话，是否只需要将.param 和.bin 替换为用ncnn量化好的int文件，然后在YOLOv5.cpp 中打开opt.use_int8_inference就可以了呢（ncnn已经换成最新的版本）？   不知道是否还需要修改一些其他地方，如果上述步骤没错的话，不知道为什么速度并没有明显提升。请问大佬有试过一些相关的加速尝试吗。谢谢您！

**Comment by cmdbug** [comment]
需要把模型按文档说明进行量化，使用量化后的模型就行，ncnn会自动判断是不是init8模型，代码不需要做任何修改。速度的话可以向ncnn提issues，速度不是很懂。

**Comment by Zr2223** [comment]
好的。非常感谢您
