### ISSUE TITLE
你好 请教下YoloV5CustomLayer

### ISSUE THREAD

**Issue by view-team** [cmdbug/YOLOv5_NCNN#66]
编译iosdemo
修正
```
#define ENABLE_CUSTOM_LAYER 1  
```

ios下编译报错

Undefined symbol: typeinfo for ncnn::Layer

**Comment by cmdbug** [comment]
顶部说明有写了，需要改或重新编译ncnn。

**Comment by view-team** [comment]
就是说官方本身提供的不支持，需要自己适配么？

**Comment by cmdbug** [comment]
不是不支持，是跟opencv参数冲突了。认真看文件顶部的说明。不行就自己新建工程，只用ncnn库。

**Comment by Xxxxi** [comment]
> 就是说官方本身提供的不支持，需要自己适配么？

你好，你是否已经解决了这个问题，是自己重新编译了ncnn库吗，可以共享下编译后的库吗，谢谢
