### ISSUE TITLE
About color space transformation

### ISSUE THREAD

**Issue by CheungBH** [cmdbug/YOLOv5_NCNN#73]
Hello. I am trying your code about SimplePose, and I feel a little confused about it.
I noticed that in both android and iOS demo, the original color space is RGBA, which uses **ncnn::Mat::PIXEL_RGBA2RGB** at the first step.  ​
https://github.com/cmdbug/YOLOv5_NCNN/blob/1ae822601e6fc41264503b56bef2aaf1cab32622/iOS_YOLOv5NCNN/YOLOv5NCNN/SimplePose.mm#L117
https://github.com/cmdbug/YOLOv5_NCNN/blob/1ae822601e6fc41264503b56bef2aaf1cab32622/android_YOLOV5_NCNN/app/src/main/cpp/SimplePose.cpp#L93

However, in the original code, it should be **ncnn::Mat::PIXEL_BGR**, which can be shown in:
https://github.com/Tencent/ncnn/blob/514770a37e49f065a2c787f8d87199b6109ae255/examples/nanodet.cpp#L256

I wonder why it is different? In my opinion, the differences will cause by:
1) You trained the model in RGB space while the original code in BGR
2) The images obtained by android and iOS is in RGBA color space

Is it right?

**Comment by cmdbug** [comment]
The images obtained by android and iOS is in RGBA color space. But the input to nanodet is BGR.

**Comment by CheungBH** [comment]
> The images obtained by android and iOS is in RGBA color space. But the input to nanodet is BGR.

But why you feed RGB images into the nanodet? 

https://github.com/cmdbug/YOLOv5_NCNN/blob/1ae822601e6fc41264503b56bef2aaf1cab32622/iOS_YOLOv5NCNN/YOLOv5NCNN/SimplePose.mm#L122
https://github.com/cmdbug/YOLOv5_NCNN/blob/1ae822601e6fc41264503b56bef2aaf1cab32622/android_YOLOV5_NCNN/app/src/main/cpp/SimplePose.cpp#L115

**Comment by cmdbug** [comment]
https://github.com/cmdbug/YOLOv5_NCNN/blob/1ae822601e6fc41264503b56bef2aaf1cab32622/android_YOLOV5_NCNN/app/src/main/cpp/NanoDet.cpp#L57

nanodet : rgba->bgr

**Comment by CheungBH** [comment]
Thank you. So the human detector in SimplePose is trained with RGB, right?

**Comment by cmdbug** [comment]
yes

**Comment by CheungBH** [comment]
Thank you
