### ISSUE TITLE
yolov5n.pt 模型转ncnn后,预测结果为空

### ISSUE THREAD

**Issue by superbayes** [cmdbug/YOLOv5_NCNN#77]
大佬,我最近使用yolov5r6官方提供的yolov5n.pt,转换为ncnn模型后无法正确预测,
我的步骤是:
1:  `python export.py --weights models/yolov5n.pt --include onnx  --train`
2: `python -m onnxsim models/yolov5n.onnx models/yolov5n-sim.onnx`
3: 在 [转换模型网址](https://convertmodel.com/) 将模型转换为 yolov5n-sim-opt-fp16 模型
4,使用yolov5进行预测,但没有结果
请up有空帮忙看看,万分感谢
[yolov5n.zip](https://github.com/cmdbug/YOLOv5_NCNN/files/7947173/yolov5n.zip)

**Comment by cmdbug** [comment]
使用示例代码 YoloV5CustomLayer 部分，原因v6版本不需要focus，所以没有自定义层了，不需要重新编译库什么的，直接使用工程就可以了。
需要修改下 jni_interface.cpp 96行左右加载的模型名称。并根据下图修改 param 参数，并修改 .h 的输出名称。压缩文件是已经修改好的，测试没有问题。
![teng_2022-01-27_11-32-36](https://user-images.githubusercontent.com/19603468/151287712-4ee77b0d-f68b-4962-955e-6cad1ee35cad.png)
[yolov5n.zip](https://github.com/cmdbug/YOLOv5_NCNN/files/7947390/yolov5n.zip)
