### ISSUE TITLE
YolactMask类属性询问

### ISSUE THREAD

**Issue by oddityyyy** [cmdbug/YOLOv5_NCNN#81]
你好！
![image](https://user-images.githubusercontent.com/90142455/159671408-156c0e7d-b4ed-467e-85a1-6afb56072c86.png)
我想请教一下maskdata和mask这两个属性保存的具体是什么数据呢？

**Comment by cmdbug** [comment]
maskdata好像没用上，mask就是这个矩形框从左上角到右下角的顺序，如果是1就是对象的像素点。
