### ISSUE TITLE
Color error

### ISSUE THREAD

**Issue by nguyentrongnhat4869** [cmdbug/YOLOv5_NCNN#84]
![photo_2022-04-07_12-21-57](https://user-images.githubusercontent.com/24762844/162125904-f027323e-af50-4ef7-ba41-77f952f0ea16.jpg)
Hi, thank you so much for your wonderful project. But I have a problem when running on virtual device of android studio. As shown in the picture, I have successfully built and run the app but in the screen the colors don't seem right. My virtual device is Pixel 4 API 30 and it says Device supports x86, but APK only supports armeabi-v7a, arm64-v8a. Looking forward to everyone's help!

**Comment by cmdbug** [comment]
I haven't tried the simulator

**Comment by nguyentrongnhat4869** [comment]
Thank you very much! I have successfully run it on real device
