### ISSUE TITLE
关于使用自己的nanodet模型会出现闪退的错误

### ISSUE THREAD

**Issue by TZzzQAQ** [cmdbug/YOLOv5_NCNN#85]
在您的项目里做了以下修改：
1、jni_interface替换了模型
2、nanodet.h以及Box.java标签以及class_num均已修改
但是还是发生了闪退错误

**Comment by cmdbug** [comment]
最新的nanodt后处理已经变了，需要参考nanodet项目示例修改后处理。

**Comment by TZzzQAQ** [comment]
> 最新的nanodt后处理已经变了，需要参考nanodet项目示例修改后处理。

大佬能说详细一点吗，本人对这一方面不是很了解
