### ISSUE TITLE
换成自己的模型后，没有检测框

### ISSUE THREAD

**Issue by SupRichard8** [cmdbug/YOLOv5_NCNN#89]

**Comment by cmdbug** [comment]
你在说什么？

**Comment by caiyongpei** [comment]
就是我把项目里面的yolov5权重文件换成自己训练的权重文件以后，手机运行检测的时候没有检测框，不知道什么原因，也没有报错

**Comment by caiyongpei** [comment]
> 你在说什么？

Box.java跟YoloV5.h里面的labels也都替换成我要检测的目标类别了，其他地方我没有动

**Comment by SupRichard8** [comment]
> 你在说什么？

作者可以留一下联系方式吗？求解决一下问题有偿

**Comment by cmdbug** [comment]
用yolov5.cpp .h 这个需要改pytorch的代码并且已经过时了，建议用yolov5customlayer.cpp .h但又跟opencv冲突需要重新编译ncnn。所以只是想玩下的话可以试试这个，原理类似，也支持Focus自定义层，把下面的工程的后处理改一下，可以参考ncnn里面的examples有yolov5的示例
https://github.com/nihui/ncnn-android-yolox

**Comment by SupRichard8** [comment]
因为需求必须要博主您的这个项目，关于ncnn重新编译因为比较紧急再加上没有接触过所以能不能加一下微信求博主帮帮忙
有偿价格您定
跪求博主帮帮忙感激不尽




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cmdbug/YOLOv5_NCNN"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月25日(星期一) 晚上6:41
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [cmdbug/YOLOv5_NCNN] 换成自己的模型后，没有检测框 (Issue #89)





 
用yolov5.cpp .h 这个需要改pytorch的代码并且已经过时了，建议用yolov5customlayer.cpp .h但又跟opencv冲突需要重新编译ncnn。所以只是想玩下的话可以试试这个，原理类似，也支持Focus自定义层，把下面的工程的后处理改一下，可以参考ncnn里面的examples有yolov5的示例
 https://github.com/nihui/ncnn-android-yolox

**Comment by cmdbug** [comment]
需要用opencv嘛，只要yolov5?

**Comment by SupRichard8** [comment]
对，只用yolov5 我自己训练的模型，就用您项目里的图像检测和摄像头实时检测
可以+v说吗: Richard_Clare


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cmdbug/YOLOv5_NCNN"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月25日(星期一) 晚上8:28
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [cmdbug/YOLOv5_NCNN] 换成自己的模型后，没有检测框 (Issue #89)





 
需要用opencv嘛，只要yolov5?

**Comment by cmdbug** [comment]
明天有空看看吧

**Comment by SupRichard8** [comment]
太感谢了！！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cmdbug/YOLOv5_NCNN"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月25日(星期一) 晚上9:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [cmdbug/YOLOv5_NCNN] 换成自己的模型后，没有检测框 (Issue #89)





 
明天有空看看吧

**Comment by cmdbug** [comment]
邮箱多少

**Comment by SupRichard8** [comment]
***@***.***
qq也是这个




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cmdbug/YOLOv5_NCNN"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月26日(星期二) 上午8:47
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [cmdbug/YOLOv5_NCNN] 换成自己的模型后，没有检测框 (Issue #89)





 
邮箱多少

**Comment by SupRichard8** [comment]
> 邮箱多少

992760989@qq.com
